# Generated by Django 4.2.5 on 2023-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_sanpham_motadai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='MauSac',
            field=models.ManyToManyField(blank=True, related_name='SanPham', to='product.mausac'),
        ),
    ]
