# Generated by Django 4.2.4 on 2023-10-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='diem_danh_gia',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')]),
        ),
    ]
